### ISSUE TITLE
Pro-level features & tweaks

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#1387]
There are several features that can be improved, need some tweaks, or need a complete re-design to reach a professional level for full-time pixel artists. These recommendations are thanks to [cyangmou](https://twitter.com/cyangmou) + some old notes/to-do items.

- [ ] New color picker ([issues](https://github.com/aseprite/aseprite/issues?q=is%3Aissue+is%3Aopen+color+picker+label%3Acolorbar)) with [RGB/HSB](https://twitter.com/cyangmou/status/818132281118363652) at the same time. Related to
- [ ] New brushes manager (#175) with [preset brushes and patterns](https://twitter.com/cyangmou/status/818191210732994566). Possibility to Import/Export brushes. Import GG brushes ([1bpp bmps](https://twitter.com/not_surt/status/818200706255437824)). Fix bug #1261
- [ ] [Rectangle/ellipse aspect ratio on status bar](https://twitter.com/cyangmou/status/818141133041766400)
- [ ] [Fill selection content changing FG color](https://twitter.com/cyangmou/status/818198910804066305) or other recolor technique. There are plans to recolor an RGB sprite as an Indexed image (all layers/all frames) which might be related to this new feature.
- [ ] Alternative mode to create planned rectangle/ellipse shapes before the final fill/stroke. ([Ref 1](https://twitter.com/cyangmou/status/818216913562193922), [Ref 2](https://twitter.com/cyangmou/status/818225457472610309))
- [ ] Pencil tool: `Shift` key to [start drawing a line from the last point with preview](https://twitter.com/cyangmou/status/818433912158429184). Dev note: `Shift` key should start a Line tool `ToolLoop`, then releasing `Shift` cancels the loop or releasing mouse button finishes the loop successfully. (Related, fix bug #1005)
- [ ] Pencil tool: `Ctrl+Shift` (or other combination)
- [ ] Contour tool: `Shift` key should start a straight line and releasing `Shift` should continue the regular freehand mode.
- [ ] Fix [rotated squared brushes](https://twitter.com/cyangmou/status/818830226654380032). We need a new specific algorithm to create these brushes.
- [ ] Fix bug #245 and #728, [continuous stroke of diagonal brushes is broken](https://twitter.com/cyangmou/status/818835604511166470)

More to read here: https://twitter.com/cyangmou/status/818881183283023872
