### ISSUE TITLE
Refactor internal selection manager

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#1459]
We need a new way to handle selection transformations, the transformation should be abstract and repeatable in several layers/cels at the same time.

Doing so we should fix:
- [ ] Undo/redo each step of selection transformations step-by-step (#424)
- [ ] Selection transformation could work on several cels at the same (#1148, #1172,  #1364)
- [ ] Selection & symmetry (#874 and #1011)
- [ ] Fix transformation handle location when we flip the selection (#1055)
- [ ] Fix selection transformation in tiled mode (#1457)
- [ ] Repeat transformation in a macro-like approach (#1378)

Review:
- [ ] Flip Horizontal/Vertical flip relative to the initial state and not the transformed state (#966)
