### ISSUE TITLE
Aseprite v1.2.x

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#1997]
**Please make a comment in this issue if you want to start working on one of these tasks.**

This is the set of items that must be seen before releasing the new Aseprite 1.2.x:

- [x] Loading TGA with alpha in palette creates a layer with Background (@Gasparoken)
- [x] Lua: Dialog:file() to add a field to select filenames https://github.com/aseprite/api/issues/7 (@dacap)
- [x] Lua: selection.origin (something to move the selection edges) (@dacap)
- [x] Check that "flash layer" is working correctly (I think this is not working on macOS) (@dacap)
- [x] https://community.aseprite.org/t/errors-with-known-color-profile-srgb/2656 (@dacap)
- [x] Pixels should be blended with normal blend mode when the backdrop is transparent pixel #1096 
   https://steamcommunity.com/app/431730/discussions/2/1739980540113413481/?tscn=1548381128 (@Gasparoken)
- [x] Create a filter command to add an outline to borders (related to #371, #1198) (@dacap)
   - ~~In someway the outline could be calculated with the whole sprite render result (instead of using the active layer only)~~ converted into #2398
- [x] radial gradient (https://community.aseprite.org/t/radial-gradient/2711, https://steamcommunity.com/app/431730/discussions/1/3182216552785250054/ ) (@dacap)
- [x] Edit > Shift feature removing sprite parts permanently (can't undo)
  https://steamcommunity.com/app/431730/discussions/2/1741103267304924778/ (@Gasparoken)
- [x] ~~https://community.aseprite.org/t/cant-browse-folders-when-saving-loading-files/1133~~
- [x] Export name same as file name by default #1964 (@Gasparoken)
- [x] Review the padding checkbox preference for Import Sprite Sheet (@Gasparoken)
- [x] Lua:  API to load/save one frame images only directly (https://github.com/aseprite/api/issues/9) (@dacap)
- [x] Test #1977 manually in release mode for bigger lines (@dacap)
- [x] https://community.aseprite.org/t/aseprite-icon-for-ase-files-is-a-bunny-now/2661 (@dacap)
- [x] Lua: https://community.aseprite.org/t/get-selected-palette-color-s/2512 (@dacap)
- ~~Lua: Image:drawImage() should use NORMAL blend mode (add blend mode)~~ https://github.com/aseprite/api/issues/31
- [x] Sprite sheet JSON exporter outputs full filesystem path in meta.image #1606

Not essential (maybe v1.2.11 or v1.3):

- [x] Script in extensions #1949
- [x] Calculate sprite sheet size correctly when trim option is enabled (use DocExporter to calculate sprite sheet texture size in the future)
- [x] Native dialog on macOS stay open after selecting a file #1917 (#1974, #1835)
