### ISSUE TITLE
Add warning to script functions with the format 'object:<function>(<some obj member>)'

### ISSUE THREAD

**Issue by Gasparoken** [aseprite/aseprite#3135]
The following functions don't take into account whether the argument object belongs to the parent object to which the function is applied:

 - [x] sprite:**deleteLayer**(layer) #3137 
 - [x] sprite:**deleteCel**(layer, frame) #3138
 - [x] sprite:**deleteSlice**(slice) (it even crashes) #3139
 - [x] sprite:**deleteTag**(tag) (unexpected behavior) #3140 

* Aseprite version: 1.2.32-x64
* System: MacOS/Windos/Linux

**Comment by dacap** [comment]
All PRs merged in 653931c4fcb8a890deefd4a5244d3b62fb0856b0
