### ISSUE TITLE
New (new) timeline

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#3904]
We're going to work on several changes for the timeline that might introduced new bugs, and we'll try to use the `beta` branch (Beta Steam channel for customers) to release v1.3.1-beta1 (the beta will exist for short periods of times, it will not be as the old beta that took years to finally be merged with `main`).

This is prioritized from several features from https://github.com/aseprite/Attachment-System/issues/9, but some features are long-waited from users:

- [ ] As a first step we would like to introduce the possibility to collapse tags  (#920, https://community.aseprite.org/t/request-collapse-tags/3349)
- [ ] Then we should be able to show only one tag in the timeline (https://github.com/aseprite/Attachment-System/issues/55)
- [ ] And stack/preview several tags in any order (tags might have an "main animation" tag so we can differentiate/arrange "big tags/main animations" easily)
- [ ] We can then review more issues from https://github.com/aseprite/Attachment-System/issues/9
- [ ] Finally we could review some features from the old #293 (hide specific frames, #244?)

To do this we'll do some refactors and introduce a new `view` module/library to convert the Timeline/DocRange as more abstract (non-UI) concepts. The Timeline must be an abstract view of the layers/frames that could be handled/tested programmatically from scripts (the same for the range, and drag-and-drop operations).
