### ISSUE TITLE
Tasks for release v1.1.1

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#845]
Tasks for v1.1.1:
- [x] hide symmetry options in non-paint tools (https://github.com/aseprite/aseprite/commit/e5397d9ad3dd748de402d17b00d4bc1d7840d8b9)
- [x] pixel perfect is not working when symmetry mode is on (https://github.com/aseprite/aseprite/commit/f4373ffbc5e6a44059d595c8ad2c955e6ee172e6)
- [x] symmetry axis isn't displayed correctly when tiled mode is on (https://github.com/aseprite/aseprite/commit/3c97f08e4eb97b2e998c2c1c9efc8a0c19d42541)
- [x] symmetry doesn't work when cel origin != 0,0 (https://github.com/aseprite/aseprite/commit/08a04fcb64faf1f3a7ae267260ac8e9561b9bda3)
- [x] preview for effects isn't working (when zoom is < 100%) (https://github.com/aseprite/aseprite/commit/c12cb26875253b41bf5cca7e1f0cdb336ecce431)
- [x] bug in OS X with update dirty lines (when maximize window or change window size, not 100% reproducible)
- [x] Text tool steals copy buffer #839
- [x] Zoom in/out shortcuts inconsistent on OS X #816
- [x] Shading mode doesn't work on index 0 #794
- [x] after fixing #839 now text tool doesn't work on grayscale or indexed
- [x] cache font preview in fonts popup
- [x] selection edges don't stop flood fill #823
- [x] export frame tags information in JSON
- [x] Add --ignore-invisible-layer option for CLI #805
- [x] Symmetry doesn't work right for even brush sizes (2px, 4px, etc.)

**Comment by oceanhahn** [comment]
Out of curiousity, are these a selection of the bugs, features, and tools selected for the next release, or is it meant to be exhaustive of all of the issues we can expect to see cleared for v1.1? :)

(I ask because I'm curious about the fate of my Issue #823.. ;) )

**Comment by dacap** [comment]
Hi @oceanhahn, this is the list of planned tasks to be done for the next release v1.1.1 to avoid delaying it even more (there are important fixes that I'd like to release ASAP).

The idea is to release v1.1.1 this week, if I've time to fix more issues (like #823) I'll try it, in other case it will be for v1.1.2 (Actually v1.1 serie is already quite big, it contains features from v1.3, so I think I'll move all new features to v1.2 and keep bug fixes on v1.1 series to release fixes sooner.)

**Comment by JoEschner** [comment]
Hey there, you mentioned "export frame tags information in JSON". But I can't find any tag informations in the JSON file. I am using Aseprite on Ubuntu 15.10.

**Comment by dacap** [comment]
Hi @JoEschner, the tags information can be exported using `--data` and `--list-tags` options from the command line. I'll add the option in the UI (File > Export Sprite Sheet) in v1.1.2.

**Comment by JoEschner** [comment]
Thanks a lot @dacap, works fine. The general structure with the "x 0.ase" / "x 1.ase" naming is quiet hard to put in a DOM context. Maybe that's not a topic for the comment section. Is there a place to discuss/read about the way it's meant to be parsed?

**Comment by dacap** [comment]
@JoEschner You can use [--filename-format](http://www.aseprite.org/docs/cli/#filename-format) to change the way naming is formatted in the JSON output.

**Comment by JoEschner** [comment]
Very interesting! Thanks
